base_user_password: devops101
allow_passwd_ssh_connection: "yes"
ssh_public_key: ~

ansible_user: root


## Which environment to setup
formation_ansible: yes
docker_state: present

testvar: prout


## K8S configuration

local_kubeconfig_path: ~/.kube/k3s.kubeconfig

ingress_nginx_chart_version: 4.1.4

ingress_nginx_chart_values:
  replicats: 2

certmanager_chart_version: 1.9.1

certmanager_chart_values:
  installCRDs: true

argocd_chart_version: 5.19.7 # argocd chart values: see role template