- hosts: k3s_cluster
  become: yes
  roles:
    - name: xanmanning.k3s

- hosts: localhost
  tasks:
    - name: Slurp k3s_kubeconfig
      slurp:
        src: /etc/rancher/k3s/k3s.yaml
      delegate_to: k3s-cp0
      register: k3s_kubeconfig
      no_log: true

    - name: write k3s kubeconfig locally
      copy:
        content: "{{ k3s_kubeconfig['content'] | b64decode | replace('127.0.0.1', hostvars['k3s-cp0'].ansible_host) }}"
        dest: ~/.kube/k3s.kubeconfig
      no_log: false
