apiVersion: v1
kind: Namespace
metadata:
  name: kube-prometheus-stack
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  destination:
    namespace: kube-prometheus-stack
    server: https://kubernetes.default.svc
  project: tooling
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 42.1.1
    helm:
      values: |
        grafana:
          enabled: true
          ingress:
            enabled: true
            path: /
            hosts:
              - grafana.kluster.ptych.net
            tls:
              - hosts:
                - grafana.kluster.ptych.net
                secretName: grafana-tls-cert
            annotations:
              kubernetes.io/tls-acme: "true"
              kubernetes.io/ingress.class: nginx
              cert-manager.io/cluster-issuer: letsencrypt-prod
       