apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: tooling
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: 1.10.1
    helm:
      values: ""