apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docker-registry 
  namespace: argocd
spec:
  destination:
    namespace: docker-registry
    server: https://kubernetes.default.svc
  project: tooling
  source:
    repoURL: https://helm.twun.io
    chart: docker-registry
    targetRevision: 2.2.2
    helm:
      values: |
        ingress:
          enabled: true
          path: /
          hosts:
            - registry.kluster.ptych.net
          tls:
            - hosts:
              - registry.kluster.ptych.net
              secretName: docker-registry-tls-cert
          annotations:
            kubernetes.io/tls-acme: "true"
            cert-manager.io/cluster-issuer: letsencrypt-prod
            nginx.ingress.kubernetes.io/proxy-body-size: "0" # important pour mettre une max body size illimitée pour nginx et pouvoir pousser des grosses images de plusieurs Gio
        persistence:
          enabled: true
          size: 50Gi
        service:
          port: 5000
          type: ClusterIP
        replicaCount: 1
        secrets:
          htpasswd: 'stagiaire:$2y$05$5BfnjRpaDyBYPpWjimrdX.20y29Uu/bVWKO8ind69YrhIRY581NNa' #unregistryasoicestimportant
